### ISSUE TITLE
Unable to compile with PHP 7.3 dev on CentOS and Ubuntu

### ISSUE THREAD

**Issue by saqirzzq** [krakjoe/pthreads#769]
I'm unable to compile pThreads master on CentOS 6.9 and 7 and Ubuntu 16.04 using PHP 7.2 and 7.3 dev.

Here is the error I'm getting. 

https://prnt.sc/gzj8wx

In file included from /root/autoconf-2.69/php-src/ext/pthreads/php_pthreads.c:51:0:
./src/copy.h: In function ‘pthreads_copy_statics’:
./src/copy.h:64:54: error: ‘zend_ast_ref’ has no member named ‘ast’
       ZVAL_NEW_AST(&copy, zend_ast_copy(Z_AST_P(next)->ast));
                                                      ^
./src/copy.h: In function ‘pthreads_copy_literals’:
./src/copy.h:131:9: error: ‘IS_CONSTANT’ undeclared (first use in this function)
    case IS_CONSTANT:
         ^
./src/copy.h:131:9: note: each undeclared identifier is reported only once for each function it appears in
make: *** [php_pthreads.lo] Error 1

Below is complete script I have been using for compiling it without any issues before. 

wget http://ftp.gnu.org/gnu/autoconf/autoconf-2.69.tar.gz
tar xvfvz autoconf-2.69.tar.gz
cd autoconf-2.69
./configure
make && make install

yum -y groupinstall 'Development Tools'
yum -y groupinstall 'Development Libraries'

yum -y install bison autoconf pkgconfig git-core libtool-ltdl readline-devel mysql mysql-devel mysql-lib libxml2-devel bzip2-devel.x86_64 libcurl-devel.x86_64 enchant-devel libjpeg-devel libpng-devel freetype-devel libicu-devel aspell-devel.x86_64 libxslt libxslt.x86_64 libxslt-devel.x86_64 valgrind-devel

rm -rf /etc/php7
mkdir -p /etc/php7
mkdir -p /etc/php7/cli
mkdir -p /etc/php7/etc
rm -rf php-src

git clone https://github.com/php/php-src.git --depth=1
cd php-src/ext
git clone https://github.com/krakjoe/pthreads -b master pthreads
cd ..

./buildconf --force

CONFIGURE_STRING="--prefix=/etc/php7 --with-bz2 --with-zlib --enable-zip --disable-cgi \
   --enable-soap --enable-intl --with-mcrypt --with-openssl --with-readline --with-curl \
   --enable-ftp --enable-mysqlnd --with-mysqli=mysqlnd --with-pdo-mysql=mysqlnd \
   --enable-sockets --enable-pcntl --with-pspell --with-enchant --with-gettext \
   --with-gd --enable-exif --with-jpeg-dir --with-png-dir --with-freetype-dir --with-xsl \
   --enable-bcmath --enable-mbstring --enable-calendar --enable-simplexml --enable-json \
   --enable-hash --enable-session --enable-xml --enable-wddx --enable-opcache \
   --with-pcre-regex --with-config-file-path=/etc/php7/cli \
   --with-config-file-scan-dir=/etc/php7/etc --enable-cli --enable-maintainer-zts \
   --with-tsrm-pthreads --enable-debug --enable-fpm \
   --with-fpm-user=www-data --with-fpm-group=www-data"

./configure $CONFIGURE_STRING

make && make install

chmod o+x /etc/php7/bin/phpize
chmod o+x /etc/php7/bin/php-config

cd ext/pthreads*

/etc/php7/bin/phpize
./configure --prefix='/etc/php7' --with-libdir='/lib/x86_64-linux-gnu' --enable-pthreads=shared --with-php-config='/etc/php7/bin/php-config'

make && make install

cd ../../
cp -r php.ini-production /etc/php7/cli/php.ini
sed -i 's/;date.timezone =.*/date.timezone = Africa\/Lagos/' /etc/php7/cli/php.ini
cp /etc/php7/etc/php-fpm.conf.default /etc/php7/etc/php-fpm.conf
cp /etc/php7/etc/php-fpm.d/www.conf.default /etc/php7/etc/php-fpm.d/www.conf
cp sapi/fpm/init.d.php-fpm /etc/init.d/php7-fpm
sed -i 's/Provides:          php-fpm/Provides:          php7-fpm/' /etc/init.d/php7-fpm
sed -i 's#^php_fpm_BIN=.*#php_fpm_BIN=/usr/sbin/php7-fpm#' /etc/init.d/php7-fpm
sed -i 's#^php_fpm_CONF=.*#php_fpm_CONF=/etc/php7/etc/php-fpm.conf#' /etc/init.d/php7-fpm
sed -i 's#^php_fpm_PID=.*#php_fpm_PID=/var/run/php7-fpm.pid#' /etc/init.d/php7-fpm

cp php.ini-production /etc/php7/cli/php-cli.ini
echo "extension=pthreads.so" > /etc/php7/cli/php-cli.ini

echo "zend_extension=opcache.so" >> /etc/php7/cli/php.ini
ln --symbolic /etc/php7/bin/php /usr/bin/php
ln --symbolic /etc/php7/sbin/php-fpm /usr/sbin/php7-fpm
chmod +x /etc/init.d/php7-fpm
update-rc.d php7-fpm defaults
service php7-fpm start

Please let me know if more details are needed.

**Comment by tpunt** [comment]
I've pushed some compatibility fixes to pthreads' master branch. If you are still having problems, then please let me know.
