### ISSUE TITLE
Not compiling on windows

### ISSUE THREAD

**Issue by chibisuke** [krakjoe/pthreads#45]
Unfortunately it seams the current version does not compile on windows with php 5.4.
Neither me nor my compiler seams to have any clue of what a "smart_str*" is surposed to be.

```
ext\pthreads\src\store.c(287) : warning C4113: 'apply_func_args_t' weicht in der Parameterliste von 'apply_func_t' ab
ext\pthreads\src\store.c(301) : error C2275: 'smart_str': Ungültige Verwendung dieses Typs als Ausdruck
        .\ext/standard/php_smart_str_public.h(30): Siehe Deklaration von 'smart_str'
ext\pthreads\src\store.c(301) : error C2065: 'psmart': nichtdeklarierter Bezeichner
ext\pthreads\src\store.c(302) : error C2065: 'psmart': nichtdeklarierter Bezeichner
ext\pthreads\src\store.c(306) : error C2065: 'psmart': nichtdeklarierter Bezeichner
ext\pthreads\src\store.c(306) : warning C4047: 'Funktion': Anzahl der Dereferenzierungen bei 'smart_str *' und 'int' unterschiedlich
ext\pthreads\src\store.c(306) : warning C4024: 'php_var_serialize': Unterschiedliche Typen für formalen und übergebenen Parameter 1
ext\pthreads\src\store.c(312) : error C2065: 'psmart': nichtdeklarierter Bezeichner
ext\pthreads\src\store.c(312) : error C2223: Der linke Teil von '->len' muss auf eine Struktur/Union zeigen
ext\pthreads\src\store.c(313) : error C2065: 'psmart': nichtdeklarierter Bezeichner
ext\pthreads\src\store.c(313) : error C2223: Der linke Teil von '->len' muss auf eine Struktur/Union zeigen
ext\pthreads\src\store.c(314) : error C2065: 'psmart': nichtdeklarierter Bezeichner
ext\pthreads\src\store.c(314) : error C2223: Der linke Teil von '->len' muss auf eine Struktur/Union zeigen
ext\pthreads\src\store.c(314) : error C2198: "calloc": Nicht genügend Argumente für Aufruf.
ext\pthreads\src\store.c(317) : error C2065: 'psmart': nichtdeklarierter Bezeichner
ext\pthreads\src\store.c(317) : error C2223: Der linke Teil von '->c' muss auf eine Struktur/Union zeigen
ext\pthreads\src\store.c(317) : error C2065: 'psmart': nichtdeklarierter Bezeichner
ext\pthreads\src\store.c(317) : error C2223: Der linke Teil von '->len' muss auf eine Struktur/Union zeigen
ext\pthreads\src\store.c(318) : error C2198: "memmove": Nicht genügend Argumente für Aufruf.
ext\pthreads\src\store.c(322) : error C2065: 'psmart': nichtdeklarierter Bezeichner
ext\pthreads\src\store.c(323) : error C2065: 'psmart': nichtdeklarierter Bezeichner
ext\pthreads\src\store.c(323) : warning C4022: 'free': Zeigertyp für übergebenen Parameter 1 stimmt nicht mit dem deklarierten Zeigertyp überein
```

Seams to be a problem that came in in 6aa99d4ab375328a6cbd8bd2e80ed4a62dee4170. VC doesn't seam to like function calls before a variable definitiv. Move the calloc (line 301) before line 298 fixes the problem.
