### ISSUE TITLE
Unable to compile with PHP 7.0.6RC1

### ISSUE THREAD

**Issue by flowl** [krakjoe/pthreads#589]
I get the following errors using the following ./configure command:

`./configure --prefix=/usr/src/php-src --with-libdir=/lib/x86_64-linux-gnu/ --with-openssl=/usr --with-curl=/usr --with-config-file-path=:/usr/src/php-src/etc --enable-gd-native-ttf --enable-mysqlnd --enable-opcache --enable-pcntl --enable-debug --enable-maintainer-zts --enable-pthreads --enable-mbstring --enable-bcmath --enable-exif --enable-ftp --enable-shmop --enable-soap --enable-sockets --enable-sysvmsg --enable-sysvsem --enable-sysvshm --enable-wddx --enable-opcache --enable-zip --enable-dba`

In file included from /usr/src/php-src/ext/pthreads/php_pthreads.c:30:0:
ext/pthreads/src/object.h:41:1: warning: "/*" within comment [-Wcomment]
 /* {{{ */
 ^
In file included from /usr/src/php-src/Zend/zend_modules.h:26:0,
                 from /usr/src/php-src/Zend/zend_API.h:27,
                 from /usr/src/php-src/main/php.h:39,
                 from ext/pthreads/src/pthreads.h:37,
                 from /usr/src/php-src/ext/pthreads/php_pthreads.c:22:
ext/pthreads/classes/threaded.h: In function 'zim_Threaded_extend':
/usr/src/php-src/Zend/zend_compile.h:511:39: error: 'zend_execute_data' has no member named 'called_scope'
 #define EX(element)    ((execute_data)->element)
                                       ^
ext/pthreads/classes/threaded.h:325:29: note: in expansion of macro 'EX'
     zend_do_inheritance(ce, EX(called_scope));
                             ^
In file included from /usr/src/php-src/Zend/zend.h:31:0,
                 from /usr/src/php-src/main/php.h:35,
                 from ext/pthreads/src/pthreads.h:37,
                 from /usr/src/php-src/ext/pthreads/php_pthreads.c:22:
/usr/src/php-src/Zend/zend_compile.h:511:39: error: 'zend_execute_data' has no member named 'called_scope'
 #define EX(element)    ((execute_data)->element)
                                       ^
/usr/src/php-src/Zend/zend_types.h:601:5: note: in definition of macro 'ZVAL_BOOL'
    (b) ? IS_TRUE : IS_FALSE; \
     ^
/usr/src/php-src/Zend/zend_API.h:632:31: note: in expansion of macro 'RETVAL_BOOL'
 #define RETURN_BOOL(b)      { RETVAL_BOOL(b); return; }
                               ^
ext/pthreads/classes/threaded.h:330:5: note: in expansion of macro 'RETURN_BOOL'
     RETURN_BOOL(instanceof_function(ce, EX(called_scope)));
     ^
ext/pthreads/classes/threaded.h:330:41: note: in expansion of macro 'EX'
     RETURN_BOOL(instanceof_function(ce, EX(called_scope)));
                                         ^
In file included from /usr/src/php-src/ext/pthreads/php_pthreads.c:442:0:
ext/pthreads/classes/pool.h: In function 'zim_Pool_submit':
ext/pthreads/classes/pool.h:141:8: warning: unused variable 'working' [-Wunused-variable]
  zval *working = NULL;
        ^
In file included from /usr/src/php-src/ext/pthreads/php_pthreads.c:47:0:
/usr/src/php-src/ext/pthreads/php_pthreads.c: At top level:
ext/pthreads/src/copy.h:313:13: warning: 'pthreads_copy_function_ctor' defined but not used [-Wunused-function]
 static void pthreads_copy_function_ctor(zval *bucket) {
             ^
Makefile:1288: recipe for target 'ext/pthreads/php_pthreads.lo' failed
make: *** [ext/pthreads/php_pthreads.lo] Error 1

**Comment by flowl** [comment]
Same with PHP 7.0.5 - besides warnings, error: 'zend_execute_data' has no member named 'called_scope'

**Comment by mrsimonbennett** [comment]
@flowl Any updates on how you solved this?
