### ISSUE TITLE
Pthreads Extension Not Compiling with PHP 7.3.0 DEV

### ISSUE THREAD

**Issue by darkphase** [krakjoe/pthreads#766]
Platform: Windows 10 
Compiler: VC15 
PHP: Latest From Git
php_pthreads: Latest From Git
 
Compilation stops giving:
"NMAKE : fatal error U1073: don't know how to make 'ext\pthreads\src\globals.c'"

**Comment by tpunt** [comment]
Hmm, I'm not receiving compilation errors (on OS X), but I am receiving runtime errors. I'll do some digging, but I doubt I'll be able to fix your issue without the same environment setup. Is anything else output about the error?

**Comment by darkphase** [comment]
Investigating config.w32 but found nothing out of ordinary...
last compilation errors are:
--
..\pecl\pthreads\php_pthreads.c(178): warning C4101: 'instance': unreferenced local variable
..\pecl\pthreads\php_pthreads.c(828): warning C4113: 'int (__cdecl *)()' differs in parameter lists from 'user_opcode_handler_t'
..\pecl\pthreads\php_pthreads.c(829): warning C4113: 'int (__cdecl *)()' differs in parameter lists from 'user_opcode_handler_t'
..\pecl\pthreads\classes/pool.h(111): warning C4018: '<': signed/unsigned mismatch
NMAKE : fatal error U1073: don't know how to make 'ext\pthreads\src\globals.c'
-- 

Interestingly libui wrapper also needs pthreads.lib compiles without problem

**Comment by schwindy** [comment]
Not sure if related, I am also unable to compile the latest (or any version...) of pthreads using PHP-7.2 branch on CentOS 7.

ext/pthreads/src/copy.h:64:7: warning: implicit declaration of function ‘ZVAL_NEW_AST’ [-Wimplicit-function-declaration]
       ZVAL_NEW_AST(&copy, zend_ast_copy(Z_AST_P(next)->ast));
       ^
ext/pthreads/src/copy.h:64:54: error: ‘zend_ast_ref’ has no member named ‘ast’
       ZVAL_NEW_AST(&copy, zend_ast_copy(Z_AST_P(next)->ast));
                                                      ^
ext/pthreads/src/copy.h: In function ‘pthreads_copy_literals’:
ext/pthreads/src/copy.h:131:9: error: ‘IS_CONSTANT’ undeclared (first use in this function)
    case IS_CONSTANT:
         ^
ext/pthreads/src/copy.h:131:9: note: each undeclared identifier is reported only once for each function it appears in
In file included from /root/php-src/ext/pthreads/php_pthreads.c:51:0:
/root/php-src/ext/pthreads/php_pthreads.c: At top level:
ext/pthreads/src/copy.h:286:23: warning: ‘pthreads_copy_function’ defined but not used [-Wunused-function]
 static zend_function* pthreads_copy_function(zend_function function) {
                       ^
make: ** [ext/pthreads/php_pthreads.lo] Error 1

Attempting to compile with PHP-7.1.11 has far more verbose error output 😞

**Comment by ikkysleepy** [comment]
Getting the same errors on ubuntu 16.0.4 with php 7.3 dev

```
In file included from /home/ubuntu/php-src/ext/pthreads/php_pthreads.c:51:0:
ext/pthreads/src/copy.h: In function ‘pthreads_copy_statics’:
ext/pthreads/src/copy.h:64:7: warning: implicit declaration of function ‘ZVAL_NEW_AST’ [-Wimplicit-function-declaration]
       ZVAL_NEW_AST(&copy, zend_ast_copy(Z_AST_P(next)->ast));
       ^
ext/pthreads/src/copy.h:64:54: error: ‘zend_ast_ref {aka struct _zend_ast_ref}’ has no member named ‘ast’
       ZVAL_NEW_AST(&copy, zend_ast_copy(Z_AST_P(next)->ast));
                                                      ^
ext/pthreads/src/copy.h: In function ‘pthreads_copy_literals’:
ext/pthreads/src/copy.h:131:9: error: ‘IS_CONSTANT’ undeclared (first use in this function)
    case IS_CONSTANT:
         ^

```

**Comment by schwindy** [comment]
I just pulled the latest 7.2 (last commit was 5 hours ago: https://github.com/php/php-src/commit/68c0c690572dc9829e84901003f0c75d55430299

and did a fresh clone. I was able to compile this time, so it looks like they fixed it, for branch `PHP-7.2` at least 🙊

**Comment by dktapps** [comment]
The changes that caused this were committed to php-src master only. This is the commit that changed it: https://github.com/php/php-src/commit/ef5ea48741a1d227a10a6654c1a8cc2f02dd414f

**Comment by tpunt** [comment]
There's actually been a few ABI breakages in the php-src master branch recently, including:
 - php/php-src@ef5ea48
 - php/php-src@39ded1d5f85ca3358cc8a52bb37e72a5eb5ce0db
 - php/php-src@e70618aff6f447a298605d07648f2ce9e5a284f5

The first two are trivial to fix (I have local fixes for them already), but the third is quite a lot more complex. I'll try and find some time to look into it soon.

**Comment by tpunt** [comment]
Ok, I think pthreads master is now compatible with php-src master (in 6710b66). Can anyone confirm please?

**Comment by dktapps** [comment]
Working fine for me (tested on Windows 10 64-bit and Ubuntu 16.04 64-bit). All tests are fine except for `Test exception handler inheritance (options) [ext/pthreads/tests/exception-handler-options.phpt]`, but that's been broken since 7.2 initial.

**Comment by tpunt** [comment]
Good to hear, thanks!

Yeah, I've noticed that test failure as well (on Travis builds). I'm having problems reproducing it locally, though. I'll see if I can set up a better dev environment later for this.

**Comment by darkphase** [comment]
Still I'm not able compile it...

PHP : 202e7ce65ccb79369ca76120c4d933d2e79ca7da
PTHREADS: 6710b66033798e3bd42ab6713979a0ecb681c586
HOST: x64
TARGET:x32
OS: WINDOWS

php_pthreads.c
..\pecl\pthreads\src/copy.h(217): error C2065: 'orig_literals': undeclared identifier
..\pecl\pthreads\src/copy.h(220): error C2065: 'orig_literals': undeclared identifier
..\pecl\pthreads\classes/pool.h(111): warning C4018: '<': signed/unsigned mismatch
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.11.25503\bin\HostX86\x86\cl.exe"' : return code '0x2'
Stop.

**Comment by tpunt** [comment]
Oops, sorry, it looks like I messed up the variable naming. This should be fixed now.

**Comment by darkphase** [comment]
My First Post still prevails..

php_pthreads.c
..\pecl\pthreads\classes/pool.h(111): warning C4018: '<': signed/unsigned mismatch
NMAKE : fatal error U1073: don't know how to make 'ext\pthreads\src\globals.c'
Stop.

**Comment by darkphase** [comment]
My First Post still prevails..

php_pthreads.c
..\pecl\pthreads\classes/pool.h(111): warning C4018: '<': signed/unsigned mismatch
NMAKE : fatal error U1073: don't know how to make 'ext\pthreads\src\globals.c'
Stop.

**Comment by tpunt** [comment]
Is there any more information on the compilation error(s)? I'll reopen this for now, and see if I can setup another dev environment to reproduce these problems.

**Comment by darkphase** [comment]
Compiler only prints out: (both static and shared compilation)

"cl.exe" /D _USRDLL /D PHP7DLLTS_EXPORTS /D PHP_EXPORTS /D LIBZEND_EXPORTS /D TSRM_EXPORTS /D SAPI_EXPORTS /D WINVER=0x0601 /D COMPILE_DL_IMAP /D COMPILE_DL_INTL /D COMPILE_DL_OPCACHE /D COMPILE_DL_OPENSSL /D COMPILE_DL_UI /I "D:\Sphere\PHP\phpdev\vc15\x86\deps\include" /DHAVE_PTHREAD_H=1 /DHAVE_SCHED_H=1 /DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 /I..\pecl\pthreads /nologo /I . /I main /I Zend /I TSRM /I ext /D _WINDOWS /D WINDOWS=1 /D ZEND_WIN32=1 /D PHP_WIN32=1 /D WIN32 /D _MBCS /W3 /D _USE_MATH_DEFINES /FD /wd4996 /D_USE_32BIT_TIME_T=1 /Zc:inline /MP8 /LD /MD /W3 /Ox /D NDebug /D NDEBUG /D ZEND_WIN32_FORCE_INLINE /GF /D ZEND_DEBUG=0 /D ZTS=1 /I "D:\Sphere\PHP\phpdev\vc15\x86\deps\include" /D FD_SETSIZE=256 /DHAVE_ARGON2ID_HASH_RAW=1 /FoD:\Sphere\PHP\phpdev\vc15\x86\php-src\Release_TS\pecl\pthreads\ /FpD:\Sphere\PHP\phpdev\vc15\x86\php-src\Release_TS\pecl\pthreads\ /FRD:\Sphere\PHP\phpdev\vc15\x86\php-src\Release_TS\pecl\pthreads\ /FdD:\Sphere\PHP\phpdev\vc15\x86\php-src\Release_TS\pecl\pthreads\ /c ..\pecl\pthreads\php_pthreads.c
php_pthreads.c
..\pecl\pthreads\classes/pool.h(111): warning C4018: '<': signed/unsigned mismatch
NMAKE : fatal error U1073: don't know how to make 'ext\pthreads\src\globals.c'
Stop.

**Comment by darkphase** [comment]
Only Remaining Error... Is this because of config.w32?
php_pthreads.c
NMAKE : fatal error U1073: don't know how to make 'ext\pthreads\src\globals.c'

**Comment by tpunt** [comment]
@darkphase I've pushed a fix to the [fix-win-config](https://github.com/krakjoe/pthreads/tree/fix-win-config) branch. Can you check to see if it works?

@dktapps It looks as though you do some Windows development - do you see any problems with the fix?

**Comment by dktapps** [comment]
@tpunt looks good to me - other extensions use this as well (zip, intl etc). Have also tested (move to something other than ext/pthreads), everything is fine.

**Comment by tpunt** [comment]
Great, thanks for the confirmation @dktapps. I've merged it into master (as f2273c08e8a13d36483510ba407d706e28ca0315) now, with the AppVeyor build passing.
