### ISSUE TITLE
The latest version can't compile in php-5.3.24

### ISSUE THREAD

**Issue by geekwolf** [krakjoe/pthreads#255]
question:
In file included from /usr/src/php-5.3.24/ext/pthreads-0.1.0/php_pthreads.c:238:
./classes/thread.h: In function ‘zim_Thread_kill’:
./classes/thread.h:473: error: ‘SIGUSR1’ undeclared (first use in this function)
./classes/thread.h:473: error: (Each undeclared identifier is reported only once
./classes/thread.h:473: error: for each function it appears in.)
In file included from /usr/src/php-5.3.24/ext/pthreads-0.1.0/php_pthreads.c:242:
./classes/worker.h: In function ‘zim_Worker_kill’:
./classes/worker.h:380: error: ‘SIGUSR1’ undeclared (first use in this function)
make: **\* [php_pthreads.lo] Error 1

I have been trying to use the pthreads1.0.1、1.0.0、0.1.0 、0.0.45、 0.0.44，but only 0.0.44 can complie successfully
