### ISSUE TITLE
pthreads cannot build with PHP 7.3 RC5

### ISSUE THREAD

**Issue by kasuganosoras** [krakjoe/pthreads#914]
Environment
==========

  * PHP: PHP 7.3.0RC5 (cli) (built: Nov 14 2018 00:01:34) ( ZTS )
  * pthreads: no
  * OS: CentOS 7.5

Summary
======

I can't build pthreads in my server, my php version is 7.3 RC5, but I can build it on my PHP 7.2.7 server with the same code.
I try to copy the `pthreads.so` from PHP 7.2 server to PHP 7.3 server, but when I run the command `php -v` in PHP 7.3 server, I got an error:

```
PHP Warning:  PHP Startup: Unable to load dynamic library 'pthreads.so' (tried: /usr/local/php/ext/pthreads.so (/usr/local/php/ext/pthreads.so: undefined symbol: _zval_ptr_dtor), /usr/local/php/ext/pthreads.so.so (/usr/local/php/ext/pthreads.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
```

Reproducing Code
==============

My build command
```
git clone https://github.com/krakjoe/pthreads
cd pthreads/
/usr/local/php/bin/phpize
./configure --with-php-config=/usr/local/php/etc/php.ini
make
make install ( not run )
```

Expected Output
=============

```
Build complete.
Don't forget to run 'make test'.
```

Actual Output
============

```
/root/pthreads/src/prepare.c: In function ‘pthreads_preparation_copy_trait_method_reference’:
/root/pthreads/src/prepare.c:830:6: error: ‘zend_trait_method_reference’ has no member named ‘ce’
  copy->ce = pthreads_prepared_entry(thread, (zend_class_entry*) reference->ce);
      ^
/root/pthreads/src/prepare.c:830:74: error: ‘zend_trait_method_reference’ has no member named ‘ce’
  copy->ce = pthreads_prepared_entry(thread, (zend_class_entry*) reference->ce);
                                                                          ^
make: *** [Makefile:204: src/prepare.lo] Error 1
```

The full error output is in: https://cdn.tcotp.cn:4443/assets/pthreads_error.txt

Thank.

**Comment by smallXueTu** [comment]
我也遇到了跟你一样的问题 你请问解决了吗 我看你也是搞MC的！

**Comment by kasuganosoras** [comment]
> 我也遇到了跟你一样的问题 你请问解决了吗 我看你也是搞MC的！

没有，我也是想开个 PocketMine-MP 服务器，结果 pthreads 死活编译不上……难受

**Comment by smallXueTu** [comment]
> > 我也遇到了跟你一样的问题 你请问解决了吗 我看你也是搞MC的！
> 
> 没有，我也是想开个 PocketMine-MP 服务器，结果 pthreads 死活编译不上……难受

还是用7.2吧 7.2性能也不错呀 虽然比7.3少25%

**Comment by smallXueTu** [comment]
> > > 我也遇到了跟你一样的问题 你请问解决了吗 我看你也是搞MC的！
> > 
> > 
> > 没有，我也是想开个 PocketMine-MP 服务器，结果 pthreads 死活编译不上……难受
> 
> 还是用7.2吧 7.2性能也不错呀 虽然比7.3少25%

我可能记错了 好像是7.3比7.0快25%
![image](https://user-images.githubusercontent.com/36348070/50731132-309ff000-1198-11e9-8329-21f07221175d.png)
![image](https://user-images.githubusercontent.com/36348070/50731171-e66b3e80-1198-11e9-92c1-8ffda88e446d.png)

**Comment by kasuganosoras** [comment]
> > > > 我也遇到了跟你一样的问题 你请问解决了吗 我看你也是搞MC的！
> > > 
> > > 
> > > 没有，我也是想开个 PocketMine-MP 服务器，结果 pthreads 死活编译不上……难受
> > 
> > 
> > 还是用7.2吧 7.2性能也不错呀 虽然比7.3少25%
> 
> 我可能记错了 好像是7.3比7.0快25%
> ![image](https://user-images.githubusercontent.com/36348070/50731132-309ff000-1198-11e9-8329-21f07221175d.png)
> ![image](https://user-images.githubusercontent.com/36348070/50731171-e66b3e80-1198-11e9-92c1-8ffda88e446d.png)

主要是因为我的服务器编译的是 PHP 7.3，网站也在用，我所有的扩展都是 PHP 7.3 的，包括 Swoole 那些，如果要改回 7.2，很多扩展要重新编译，配置文件也要改，生产环境不敢乱动……

**Comment by dktapps** [comment]
PocketMine-MP typically uses a custom-compiled build of PHP which runs in its local install directory. For what it's worth, the performance gains by using 7.3 are relatively insignificant.

**Comment by CharlotteDunois** [comment]
@kasuganosoras https://github.com/krakjoe/pthreads/issues/910#issuecomment-448028425

**Comment by dktapps** [comment]
f55ffa9250f3856c5b542f074b45cd56c5d2db82 addresses this.

**Comment by SirSnyder** [comment]
Yes, pthreads is 7.3 compliant.

**Comment by DENR-Dave** [comment]
That's great news. Any idea when we'll see a Windows version available that will work with 7.3 (64 bit specifically)? Appreciate your work on this.

**Comment by kasuganosoras** [comment]
> [f55ffa9](https://github.com/krakjoe/pthreads/commit/f55ffa9250f3856c5b542f074b45cd56c5d2db82) addresses this.

Thank you, now pthreads is successful build on my php 7.3 server :p
![img](https://i.natfrp.org/dac2ac3a0e67960d65f7913dfdb6ab92.png)

**Comment by smallXueTu** [comment]
> > [f55ffa9](https://github.com/krakjoe/pthreads/commit/f55ffa9250f3856c5b542f074b45cd56c5d2db82) addresses this.
> 
> Thank you, now pthreads is successful build on my php 7.3 server :p
> ![img](https://camo.githubusercontent.com/ff276bdc153c2d632ca91c10c4e40c14c07c5018/68747470733a2f2f692e6e61746672702e6f72672f64616332616333613065363739363064363566373931336466646236616239322e706e67)

可以分享一下嘛

**Comment by smallXueTu** [comment]
Oh thank you I can

**Comment by smallXueTu** [comment]
![image](https://user-images.githubusercontent.com/36348070/51373022-f9d3bd80-1b39-11e9-9799-1fedcb88b41f.png)

**Comment by mnapoli** [comment]
It builds great on 7.3.1, thank you! Are there any plans to tag a release?
